travis:
  secure:
    BINSTAR_TOKEN: gE0p/gCw7wY5Ur8++wpIp3xVh5EsDicEVx+84EX49Zx7AlJHCZCE8v2j/ngS2dyCs+QS3jMA3AtrUuPdtjfCPO25f0L7rKi3Xv5xwoorLjdJXibIGwfWvQjyvZIDxI4UmiPjOTFnVKBbQYhlDFNMENrwaewnDd22j0tCsymFWw8r1WtwX6OWHvsLHUZ+daIFVnBdaa1rCN61k6UUTHCvr4GQEDvDedH8eGJ/EUp1oMovMn8wk+EZFAafYyDYYqNtiKElTc2/Oc2dShzsI8RxNWyf1PkcLTVIWO+arA1WHhTiUqfzYJeOAX7Ee5tTbvT8TxZGNfWw8mUwCBBtrHJ4QURlLsMdOwpQ64V+BQn2SFZCI/H2ppUDA12EShiJkdzPz0pdJSR3uZy67pu/pqdtMm2Fqe6a5G4Y1DQ8eqP57mqrggScBQ6VSXPSmOJOM9mYOF0KrRYBtaerfK101M68oTzUC0f7cGJ1Mjrk2PxSEg1xTybSyll562DH93bOW5ocy7J+cxWXRgiXNvNcDImQF1Pc0Ib25lZBWYwIUm4ZlEY6bQzJMeu56dX6w/PDCiYJUooLxf7CzP8M8t1C/VSuFdhpA29bm/cl+XvBLjgy+LjrsReFK2smbd2M8ToK52wGwVTY0AM60TZx4nylwDAxSxXGuB7fAvLEKCrooPQlUuo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
